---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          icon: github
          href: https://github.com/AaronYang0628
    - Aliyun:
        - abbr: Ali
          href: https://home.console.aliyun.com/home/dashboard/ProductAndService
    - FontAwesome:
        - abbr: FontA
          href: https://fontawesome.com/v6/search?o=r
    - Skywork:
        - abbr: SKY
          href: https://skywork.ai/

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
    - Bilibili:
        - abbr: BB
          href: https://bilibili.com/
