---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          icon: github
          href: https://github.com/AaronYang0628
    - Aliyun:
        - abbr: Ali
          icon: icloud
          href: https://home.console.aliyun.com/home/dashboard/ProductAndService
    - FontAwesome:
        - abbr: FA
          icon: fontawesome
          href: https://fontawesome.com/v6/search?o=r
    - Skywork:
        - abbr: SKY
          icon: slidev
          href: https://skywork.ai/
    - ICON:
        - abbr: IC
          icon: dashboard-icons-dark
          href: https://dashboardicons.com/

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          icon: youtube
          href: https://youtube.com/
    - Bilibili:
        - abbr: BB
          icon: bilibili
          href: https://bilibili.com/
