---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Basic Components:
    - Proxy[Bridge]:
        icon: haproxy
        href: http://47.110.67.161:32080/main/index
        description: GoProxy Bridge Service
    - Proxy[Client]:
        icon: haproxy
        href: http://47.110.67.161:30080/main/index
        description: GoProxy Client Service

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
