---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- logo:
  href: https://home.72602.online
  target: _blank # Optional, can be set in settings
  icon: /icons/st_icon_alpha.png

- resources:
    cpu: true
    memory: true
    disk: /
    network: true

- search:
    provider: google
    target: _blank
