apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-logs-pvc
  namespace: monitor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "standard"