baseURL = 'https://72602.online'
languageCode = 'en-us'
theme = 'hugo-theme-relearn'
[params]
  linkTitle = '72602'
  disableLandingPageButton = true
  showVisitedLinks = true
  menuPre = '<i class="fab fa-github"></i> '
  themeVariant = ['72602','auto']
  [params.search]
    disable = true

    [params.search.index]
      disable = true

    [params.search.page]
      disable = true
[menu]
  [[menu.shortcuts]]
    name = 'Parent 1'
    weight = 1

  [[menu.shortcuts]]
    name = 'Child 1'
    parent = 'Parent 1'
    url = 'https://example.com/1'

  [[menu.shortcuts]]
    name = 'Parent 2'
    weight = 2

  [[menu.shortcuts]]
    name = 'Child 2'
    parent = 'Parent 2'
    url = 'https://example.com/2'