apiVersion: batch/v1
kind: Job
metadata:
  name: hugo-build
spec:
  template:
    spec:
      ttlSecondsAfterFinished: 3600
      restartPolicy: Never
      containers:
        - name: hugo
          image: m.daocloud.io/docker.io/hugomods/hugo:exts-non-root-0.152.0
          command:
            - /bin/sh
            - -c
            - |
              ls -al
              rm -rf /output/*
              hugo --source /src --destination /output
          volumeMounts:
            - name: output
              mountPath: /output
      volumes:
        - name: output
          persistentVolumeClaim:
            claimName: hugo-blog-pvc
