apiVersion: batch/v1
kind: Job
metadata:
  name: blog-content-build
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      ttlSecondsAfterFinished: 3600
      restartPolicy: Never
      initContainers:
        - name: clone-repo
          image: m.daocloud.io/docker.io/alpine/git:latest
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p ~/.ssh
              cp /root/.ssh-secret/id_rsa ~/.ssh/id_rsa
              cp /root/.ssh-secret/known_hosts ~/.ssh/known_hosts
              chmod 600 ~/.ssh/id_rsa
              git clone --recurse-submodules git@github.com:AaronYang0628/home-site.git /src
              chown -R 1000:1000 /output /src || true
              chmod -R g+rwX /output /src || true
              chown -R 1000:1000 /src
          volumeMounts:
            - name: src
              mountPath: /src
            - name: output
              mountPath: /output
            - name: ssh-key
              mountPath: "/root/.ssh-secret"
              readOnly: true
      containers:
        - name: hugo
          image: m.daocloud.io/docker.io/hugomods/hugo:exts-non-root-0.152.0
          command:
            - /bin/sh
            - -c
            - |
              rm -rf /output/*
              hugo --source /src --destination /output
          volumeMounts:
            - name: output
              mountPath: /output
            - name: src
              mountPath: /src
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
      volumes:
        - name: output
          persistentVolumeClaim:
            claimName: hugo-blog-pvc
        - name: src
          emptyDir: {}
        - name: ssh-key
          secret:
            secretName: github-ssh-key
            defaultMode: 0600
            items:
            - key: id_rsa
              path: id_rsa
            - key: known_hosts
              path: known_hosts
      
