apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milvus-rag-app
spec:
  project: default
  source:
    repoURL: 'git@github.com:AaronYang0628/tutorial.git'
    targetRevision: main
    path: milvus/python/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: application